name: Flutter Web Build + Vercel (Example)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'apps/app/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter 3.41.x
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.0'
          channel: stable

      - name: Flutter pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build web (PWA disabled)
        run: |
          flutter build web --release --pwa-strategy=none \
            --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
            --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
            --dart-define=APP_ENV=prod \
            --dart-define=LOG_LEVEL=info

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel
          vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
          vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"

# Move this file to .github/workflows/flutter_web_vercel.yml
# if repository policy allows edits outside apps/app.
